### ISSUE TITLE
Stub front page

### ISSUE THREAD

**Issue by GregoryRhysEvans** [cybergreen-net/inventory.cybergreen.net#1]
Create a stub front page, potentially reusing the [open data handbook theme](http://opendatahandbook.org/) used on the stats site.

**Comment by GregoryRhysEvans** [comment]
Fixed.

**Comment by aaronkaplan** [comment]
> On 02 Aug 2016, at 11:42, GregoryRhysEvans notifications@github.com wrote:
> 
> Create a stub front page, potentially reusing the open data handbook theme used on the stats site.

I think we should also add some (hand-written) text to the notebook. But - can be done later..
I get the stub character of it now. Already looks good.
