### ISSUE TITLE
needed info in the inventory

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/inventory.cybergreen.net#16]
Please change the inventory.cybergreen.net project page and add the info from the following columns to the main page:
- Title
- Owner
- Homepage
- Taxonomy
- Description
- Format
- Public (use an icon if public or not public)
- Relevance
- Link to a more detailed page describing all the fields (separate sub-page per feed)

**Comment by rufuspollock** [comment]
@aaronkaplan what is "Relevance"? (Is it in the sources.csv?)

Re separate subpage per feed we planned / agreed to leave that out of this iteration and come back to that in iteration 2 on this. (I agree we want it but we need to think more about what fields and a single page view works for now).

**Comment by rufuspollock** [comment]
FIXED modulo page about fields in inventory which is #18.
