### ISSUE TITLE
Show information about inventory fields on the inventory page

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/inventory.cybergreen.net#18]
Part of #44 

We want to add and an explanation of key fields e.g. Format, Taxonomy etc (could be hover, could be a key section ...)

**Comment by zelima** [comment]
Moving to next milestone as page is not ready This milestone

**Comment by rufuspollock** [comment]
I am moving to Backlog for now as users have indicated this is not high priority (the inventory in general).

**Comment by zelima** [comment]
FIXED
