### ISSUE TITLE
Decide on sources vs feed nomenclature

### ISSUE THREAD

**Issue by GregoryRhysEvans** [cybergreen-net/inventory.cybergreen.net#2]
Which terminology should be favoured?

**Comment by rufuspollock** [comment]
@aaronkaplan any views here? (We are using "sources" as in Data Sources at the moment)

**Comment by aaronkaplan** [comment]
both are ok. In IT security generally, people working with data feeds tend to call them "feeds" or "feeders". But "sources will be understandable as well. Also , it has the benefit of being maybe a bit clearer in english.

**Comment by rufuspollock** [comment]
@aaronkaplan happy with either and let you call this one. Naming is one of those hard things in CS ;-) (feel free to ask folks ...)

**Comment by rufuspollock** [comment]
@aaronkaplan any thoughts?

**Comment by aaronkaplan** [comment]
sources

**Comment by rufuspollock** [comment]
FIXED. Decision is `sources`
