### ISSUE TITLE
Initial fields for the CSV

### ISSUE THREAD

**Issue by GregoryRhysEvans** [cybergreen-net/inventory.cybergreen.net#3]
Decide which fields should be included in the CSV

Here is the [current feed list and fields](https://docs.google.com/a/atomatic.net/spreadsheets/d/17s-Axtk0D2Cf2wDI-dKclHrV8v2FDhhPraQgP1NemHw/edit?usp=drive_web)

**Comment by rufuspollock** [comment]
@aaronkaplan any thoughts here - obviously we have the fields in the google spreadsheet. To get things started we've just stubbed a CSV with some basic columns here: https://github.com/cybergreen-net/inventory.cybergreen.net/blob/gh-pages/_data/sources.csv

**Comment by aaronkaplan** [comment]
Will send a PR.

Cool!!! Looks very slick already.

**Comment by rufuspollock** [comment]
@aaronkaplan ping ;-)

**Comment by rufuspollock** [comment]
FIXED by @aaronkaplan and me.

**Comment by aaronkaplan** [comment]
however, basically right now it shows only links to external pages. And the SPAM link does not work.
