### ISSUE TITLE
Provide description of fields in the data inventory

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/inventory.cybergreen.net#47]
@aaronkaplan the `datapackage.json` is now there:

https://github.com/cybergreen-net/inventory.cybergreen.net/blob/gh-pages/_data/datapackage.json

Each field (column) in the CSV has entry in the fields list e.g.:

          {
            "name": "Taxonomy",
            "type": "string",
            "title": "",
            "description": ""
          },

Can you edit to:

- add a title: this is optional as we already have the name. This would be appropriate where you want a slightly more useful label for the field in the UI e.g. `File Format` (title) vs `Format` (name). Just leave the title blank where you have nothing.
- add a description of the field explaining what it is. You can use markdown if you want. We will then use these descriptions when building the inventory page 😄 

NOTE: we do not necessarily need a description for every field if you think some don't need that. However, I think even obvious ones like the `Title` field could benefit from a short description IMO 😄

**Comment by aaronkaplan** [comment]
Excellent. Will do Thx. 

---
Mobile

**Comment by rufuspollock** [comment]
FIXED. We don't have this in the datapackage.json yet but we do have it in a [google spreadsheet][sheet] after a call with aaron.

[sheet]: https://docs.google.com/spreadsheets/d/1ZNoJPEkRYVq7R_-u3DDjTUA21Qie6C-Q8Gj9Bpp4yxI/edit#gid=420127306
