### ISSUE TITLE
Crop and upload new headshot for Yurie

### ISSUE THREAD

**Issue by ataslim** [cybergreen-net/inventory.cybergreen.net#50]
Headshot attached here. Please crop from her chest up, and upload to front page (center circle) and "Who We Are" page.

![yurie pic](https://cloud.githubusercontent.com/assets/22147924/20970393/64c39e3e-bc5b-11e6-88c2-1ee6e5dada37.jpg)

**Comment by ataslim** [comment]
Please use these instead. No need to crop.

![yurieheadshotbw](https://cloud.githubusercontent.com/assets/22147924/21231153/36c7e958-c2b5-11e6-91a0-e99d4f5c271f.jpg)
![yurieheadshotcolor](https://cloud.githubusercontent.com/assets/22147924/21231156/38c77098-c2b5-11e6-8edd-82ece92fc9ff.jpg)

**Comment by zelima** [comment]
@shiweiart I assume this one is done and can be closed.
Could you please confirm and close?

**Comment by rufuspollock** [comment]
FIXED. Merged and live.

**Comment by ataslim** [comment]
Please also change the headshot on the "Who We Are" page per the original issue.

**Comment by rufuspollock** [comment]
FIXED in #66.
