### ISSUE TITLE
Greenland is missing!

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/inventory.cybergreen.net#55]
Hi folks!

the map is actually quite funny. We are completely missing Greenland on the map.
Please change the map. 

(PS: same with Antarctica and the Arctic)

**Comment by rufuspollock** [comment]
INVALID. Think this is a stats site issue not a www issue.

**Comment by aaronkaplan** [comment]
If there is no data on Greenland specifically it does not mean we can simply omit Greenland from a global map. 


Rufus - you just made me laugh. 
"It's the fault of the data that we can not display Greenland". 




---
Mobile
