### ISSUE TITLE
new graph for global DDOS potential

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/inventory.cybergreen.net#57]
Please make a stacked graph of how the different risks add up to the global DDOS potential 
(please take the AF count columns for this)

**Comment by zelima** [comment]
@aaronkaplan Does this mean we should leave "units" mentioned in https://github.com/cybergreen-net/stats-new/issues/131 and stay with simple af count? Or Units for DDOS and simple af count for risks?

**Comment by aaronkaplan** [comment]
No. Add: "TBit/sec" as a unit on the y-axis and make a stacked one please.

**Comment by rufuspollock** [comment]
INVALID - wrong repo i think and DUPLICATE of https://github.com/cybergreen-net/stats-new/issues/138
