### ISSUE TITLE
Make sources/feeds filterable/searchable (?)

### ISSUE THREAD

**Issue by GregoryRhysEvans** [cybergreen-net/inventory.cybergreen.net#6]
_Not sure needed right now as we will have not many feeds_

Users should be able to filter and search the source/feed list on the front page.

Which facets should be filterable?

**Comment by aaronkaplan** [comment]
I think over the course of time we will have around > 50 or 100 feeds. I know this number roughly exists. Many of them are not high quality but we might want to list them anyway.

**Comment by aaronkaplan** [comment]
Which aspects should be filterable?
- quality related fields
- name of the feed
- openness

**Comment by rufuspollock** [comment]
@aaronkaplan we should think about user stories - what do people want do here (and who are they?)

**Comment by aaronkaplan** [comment]
yes, let's talk about user stories here.
Also we need to mark which feeds CG is actually processing and which not.
