### ISSUE TITLE
Implement design of inventory page

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/inventory.cybergreen.net#61]
Implementing resolves of  #60 
See mock ups in https://drive.google.com/open?id=0B7ucLyXmP0n2bWFoaTVCWjFPZXc

**Comment by zelima** [comment]
@rufuspollock how are we doing on this? Are we doing in this sprint?

**Comment by rufuspollock** [comment]
@zelima this is postponed - based on feedback from e.g. JP CERT this is not high priority so we are prioritizing other things atm.

**Comment by rufuspollock** [comment]
I would also add  that I've done some general UX work and now looks good. Still not sure we want to move to tabular layout.

**Comment by zelima** [comment]
Moving to backlog for now
