### ISSUE TITLE
Set up DNS for this site

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/inventory.cybergreen.net#8]
inventory.cybergreen.net works!

Want to set up DNS to point that subdomain to cybergreen-net.github.io and we add CNAME here and deploy gh-pages

@aaronkaplan can you take a look at this one (esp set up of DNS).

**Comment by aaronkaplan** [comment]
> On 09 Aug 2016, at 18:37, Rufus Pollock notifications@github.com wrote:
> 
> inventory.cybergreen.net works!
> 
> Want to set up DNS to point that subdomain to cybergreen-net.github.io and we add CNAME here and deploy gh-pages
> 
> @aaronkaplan can you take a look at this one (esp set up of DNS).

We can do that with the help of Moto-san.

**Comment by aaronkaplan** [comment]
Done 
Please Test 

---

Mobile

**Comment by rufuspollock** [comment]
FIXED. http://inventory.cybergreen.net/ works!

**Comment by aaronkaplan** [comment]
works. confirmed
