### ISSUE TITLE
Add "install" / local development instructions

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/inventory.cybergreen.net#9]
- This uses jekyll and github pages (can point to docs for this)
- Basic commands for getting started e.g. install ruby + jekyll, then run jekyll. Explain that we deploy on github pages

**Comment by GregoryRhysEvans** [comment]
Fixed. Added these.

@aaronkaplan let me know if this needs changing at some point.

**Comment by aaronkaplan** [comment]
Thanks, but could you please also add a sentence on how to deploy remotely (github, own server)?
Or just link to the howto which explains how to get this done in ruby.
Please don't assume everybody is a ruby coder.

**Comment by rufuspollock** [comment]
@GregoryRhysEvans can you add a link to github pages docs with instructions.

**Comment by GregoryRhysEvans** [comment]
@rgrp I've added this. @aaronkaplan No knowledge of ruby should be needed to deploy the site. It simply needs to be installed as a prerequisite of jekyll, as per the instructions.

**Comment by aaronkaplan** [comment]
> On 18 Aug 2016, at 11:59, GregoryRhysEvans notifications@github.com wrote:
> 
> @rgrp I've added this. @aaronkaplan No knowledge of ruby should be needed to deploy the site. It simply needs to be installed as a prerequisite of jekyll, as per the instructions.

Perfect! Thx
